import java.awt.event.*;
import javax.swing.JOptionPane;/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class frmKonversiSuhu extends javax.swing.JFrame {

    /**
     * Creates new form frmKonversiSuhu
     */
    public frmKonversiSuhu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblJudul = new javax.swing.JLabel();
        lblInput = new javax.swing.JLabel();
        txtSuhu = new javax.swing.JTextField();
        lblKonversi = new javax.swing.JLabel();
        cmbKonversi = new javax.swing.JComboBox<>();
        btnKonversi = new javax.swing.JButton();
        lblHasil = new javax.swing.JLabel();
        rdbOtomatis = new javax.swing.JRadioButton();
        rdbManual = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Konversi Suhu");

        lblJudul.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblJudul.setText("Aplikasi Konversi Suhu");

        lblInput.setText("Masukkan Suhu : ");

        txtSuhu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSuhuKeyTyped(evt);
            }
        });

        lblKonversi.setText("Pilih Konversi : ");

        cmbKonversi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celcius ke Fahrenheit", "Celcius ke Kelvin", "Celcius ke Reamur", "Fahrenheit ke Celcius", "Fahrenheit ke Kelvin", "Fahrenheit ke Reamur", "Kelvin ke Celcius", "Kelvin ke Fahrenheit", "Kelvin ke Reamur", "Reamur ke Celcius", "Reamur ke Fahrenheit", "Reamur ke Kelvin" }));
        cmbKonversi.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                cmbKonversiComponentRemoved(evt);
            }
        });

        btnKonversi.setText("Konversi");
        btnKonversi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKonversiActionPerformed(evt);
            }
        });

        lblHasil.setText("Hasil : ");

        rdbOtomatis.setText("Otomatis");
        rdbOtomatis.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rdbOtomatisItemStateChanged(evt);
            }
        });

        rdbManual.setText("Manual");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(lblJudul))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblKonversi)
                                .addGap(18, 18, 18)
                                .addComponent(cmbKonversi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblInput)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSuhu, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblHasil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(rdbOtomatis)
                        .addGap(18, 18, 18)
                        .addComponent(rdbManual))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(btnKonversi)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblJudul)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInput)
                    .addComponent(txtSuhu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKonversi)
                    .addComponent(cmbKonversi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbOtomatis)
                    .addComponent(rdbManual))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnKonversi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHasil)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbKonversiComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_cmbKonversiComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbKonversiComponentRemoved

    private void txtSuhuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSuhuKeyTyped
    char c = evt.getKeyChar();
    if (!Character.isDigit(c) && c != '.' && c != '-') {
        evt.consume();
    }
        
    }//GEN-LAST:event_txtSuhuKeyTyped

    private void btnKonversiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKonversiActionPerformed
    try {
        double suhu = Double.parseDouble(txtSuhu.getText());
        String pilihan = cmbKonversi.getSelectedItem().toString();
        double hasil = 0;
        String satuan = "";

        switch (pilihan) {
            // ==== DARI CELCIUS ====
            case "Celcius ke Fahrenheit":
                hasil = (suhu * 9 / 5) + 32; satuan = "°F"; break;
            case "Celcius ke Kelvin":
                hasil = suhu + 273.15; satuan = "K"; break;
            case "Celcius ke Reamur":
                hasil = suhu * 4 / 5; satuan = "°R"; break;

            // ==== DARI FAHRENHEIT ====
            case "Fahrenheit ke Celcius":
                hasil = (suhu - 32) * 5 / 9; satuan = "°C"; break;
            case "Fahrenheit ke Kelvin":
                hasil = (suhu - 32) * 5 / 9 + 273.15; satuan = "K"; break;
            case "Fahrenheit ke Reamur":
                hasil = (suhu - 32) * 4 / 9; satuan = "°R"; break;

            // ==== DARI KELVIN ====
            case "Kelvin ke Celcius":
                hasil = suhu - 273.15; satuan = "°C"; break;
            case "Kelvin ke Fahrenheit":
                hasil = (suhu - 273.15) * 9 / 5 + 32; satuan = "°F"; break;
            case "Kelvin ke Reamur":
                hasil = (suhu - 273.15) * 4 / 5; satuan = "°R"; break;

            // ==== DARI REAMUR ====
            case "Reamur ke Celcius":
                hasil = suhu * 5 / 4; satuan = "°C"; break;
            case "Reamur ke Fahrenheit":
                hasil = (suhu * 9 / 4) + 32; satuan = "°F"; break;
            case "Reamur ke Kelvin":
                hasil = (suhu * 5 / 4) + 273.15; satuan = "K"; break;
        }

        // tampilkan hasil di label
        lblHasil.setText(String.format("Hasil: %.2f %s", hasil, satuan));

        // jika mode manual aktif, tampilkan popup
        if (rdbManual.isSelected()) {
            JOptionPane.showMessageDialog(this, "Hasil konversi: " + hasil + " " + satuan);
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Input harus berupa angka!", "Error", JOptionPane.ERROR_MESSAGE);

    }
    }//GEN-LAST:event_btnKonversiActionPerformed

    private void rdbOtomatisItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rdbOtomatisItemStateChanged
        if (rdbOtomatis.isSelected()){
        txtSuhu.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent e) {
                    btnKonversiActionPerformed(null); // panggil tombol konversi otomatis
                }
            });
        }
    }//GEN-LAST:event_rdbOtomatisItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmKonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new frmKonversiSuhu().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKonversi;
    private javax.swing.JComboBox<String> cmbKonversi;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblHasil;
    private javax.swing.JLabel lblInput;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblKonversi;
    private javax.swing.JRadioButton rdbManual;
    private javax.swing.JRadioButton rdbOtomatis;
    private javax.swing.JTextField txtSuhu;
    // End of variables declaration//GEN-END:variables
}
